name: gpii-universal node tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run npm install
      run: npm install
    - name: Pass linter
      run: $(npm bin)/grunt lint
    - name: Run node tests
      run: node tests/all-tests.js
